# File: .github/workflows/iplcdn_repo-sync.yml
name: sync-iplcdn-scripts
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-iplcdn-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT || github.event.client_payload.PAT }}  
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync iplcdn-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/iplcdn/iplcdn_repo-sync.git"
          source_branch: "master"
          destination_branch: "main"
          github_token: ${{ secrets.PAT || github.event.client_payload.PAT }}
